"""add user rsa keys

Revision ID: a39bc03b736b
Revises: 2e3060ed59f1
Create Date: 2026-08-05 09:33:15.329916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a39bc03b736b'
down_revision: Union[str, Sequence[str], None] = '2e3060ed59f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_key', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('encrypted_private_key', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'encrypted_private_key')
    op.drop_column('users', 'public_key')
    # ### end Alembic commands ###
