"""add composite index for file listing queries

Revision ID: a8f9845cc844
Revises: a39bc03b736b
Create Date: 2026-08-06 14:24:28.348570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f9845cc844'
down_revision: Union[str, Sequence[str], None] = 'a39bc03b736b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_files_user_uploaded_at', 'files', ['user_id', 'uploaded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_files_user_uploaded_at', table_name='files')
    # ### end Alembic commands ###
